spring.application.name=news-delivery-service
server.port=${PORT:8080}

spring.datasource.url=dbc:postgresql://ep-long-field-b33oeg0g-pooler.c-4.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=${DATABASE_USERNAME:neondb_owner}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:default-secret-key-32-chars-minimum-for-local}
jwt.expiration=86400000

ingestion.service.url=${INGESTION_SERVICE_URL:https://news-ingestion-service-3.onrender.com}

spring.ai.ollama.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
spring.ai.ollama.chat.model=deepseek-r1:1.5b
spring.ai.ollama.chat.options.temperature=0.7